### PR TITLE
Analytics for AUGSD

### PR DESCRIPTION
**Pull request by vballoli**
This PR creates an analytics functionality for 
1. `admin` to view/upload student CG data 
2. `professors` to search and get the CG graph 

Furthermore, next steps involve giving registration advisers the access to this functionality based on the CSV uploaded.

### CODE REVIEW

**Comment by Kailash0311** [comment]
Thank you @vballoli for the PR. Few things need to be changed before I can actually review your PR:

1. Do not change the versions/integrity hashes of the existing packages (in `package-lock.json` or `package.json`). We would like to address them in a different PR. (This constitutes for the most changes in this PR). Make sure your PR works with the pre-existing versions of the packages. If you have used any new packages, feel free to add them :) . 
2. Use `grunt` to fix all the prettier issues. 
3. Try to use block scope variables such as `let/const` consistently.

**Comment by Kailash0311** [comment]
@sohailrajdev97 I think the reason the PRs are failing the Travis CI tests is because our `yarn.lock` file needs to be updated. Please confirm.

**Comment by vballoli** [comment]
Sorry for the late reply. I'll work on the recommended changes. Thanks a lot

**Comment by sohailrajdev97** [comment]
Bulk clean-up.

**Pull request closed without merging**
