### PR TITLE
ui: Add footer to home pages

### PR DESCRIPTION
**Pull request by hereisdx**
**Note** : Sorry for creating a new PR, this one is from a forked repository as I deleted the previous one.

As a part of the inductions, I have added a footer to both the home pages of AUGSD and TD. The footer is according to material design principles, inspired from https://getmdl.io/components/#layout-section/footer. Some modifications were also made to home layouts. The footer becomes expandable on mobiles to save space.
Screenshot from 2019-04-03 01-47-00

Screenshot from 2019-04-03 01-40-35
Screenshot from 2019-04-03 01-40-21

### CODE REVIEW

**Comment by Kailash0311** [comment]
Commit message -  `inductions: Add footer ..` can mean you are changing something in inductions portal, you didn't mean that though. Come up with something better.

**Comment by Kailash0311** [comment]
2lakh + lines of additions, again? :confused:

**Comment by hereisdx** [comment]
Footer is now in light theme. Unnecessary links have been removed. Chamber no has been added to contact info.
Screenshot from 2019-04-03 18-34-03

**Comment by Kailash0311** [comment]
Merging, thanks @hereisdx !

**Pull request merged**
